[package]
name = "did_resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
identity_iota = "1.5.1"
iota-sdk = { version = "1.1.5", default-features = true }
